using System;
using System.IO;

namespace DAL
{
    /// <summary>
    /// Singleton class to write simple text log files to save errors and messages generated by the application 
    /// </summary>
    public class Logger
    {
        static Logger logger = null;
        string path = string.Empty;
        bool canAccessPath = false;

        private Logger() {
        }

        public static Logger Create()
        {
            if (logger == null)
            {
                logger = new Logger();
            }

            if (string.IsNullOrEmpty(logger.path) || logger.path != "Log_" + DateTime.Now.ToString("dd_MM_yyyy") + ".txt")
            {
                logger.path = "Log_" + DateTime.Now.ToString("dd_MM_yyyy") + ".txt";
                try
                {
                    File.WriteAllText(logger.path, "Logger started on: " + DateTime.Now.ToLongDateString() + Environment.NewLine);
                    logger.canAccessPath = File.Exists(logger.path);
                }
                catch
                {
                    logger.canAccessPath = false;
                }
            }

            return logger;
        }

        public void Exception(Exception message)
        {
            if (canAccessPath)
            {
                File.WriteAllText(path, string.Format("[ERROR-{0}] {1}", DateTime.Now.ToLongDateString(), message.ToString()));
            }
        }

        public void Message(string message)
        {
            if (canAccessPath)
            {
                File.WriteAllText(path, string.Format("[MESSAGE-{0}] {1}", DateTime.Now.ToLongDateString(), message));
            }
        }
    }
}
